services:
# database container
  db:
    build: ./mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: cpms_lei_db
      MARIADB_USER: user
      MARIADB_PASSWORD: user123
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

# frontend/backend container
  server:
    build: ./frontend-backend
    restart: always

    # mapping the listener port 3000 of container to port 8080 of host
    ports:
      - "8080:3000"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge